export const remainingOptions = [
  { callsign: 'TSC206', classification: 'H/A332', origin: 'CYYZ' },
  { callsign: 'NSZ4469', classification: 'M/B38M', origin: 'ESSA' },
  { callsign: 'CAI24RK', classification: 'M/B38M', origin: 'LTAI' },
  { callsign: 'EUK94R', classification: 'H/A333', origin: 'KJFK' },
  { callsign: 'EZS32KB', classification: 'M/A320', origin: 'LSGG' },
  { callsign: 'CPA259', classification: 'H/A359', origin: 'VHHH' },
  { callsign: 'AEE638', classification: 'M/A320', origin: 'LGAV' },
  { callsign: 'EXS12M', classification: 'M/B738', origin: 'LCPH' },
  { callsign: 'VIR73Q', classification: 'H/A333', origin: 'KATL' },
  { callsign: 'AUA4GN', classification: 'M/A320', origin: 'LOWW' },
  { callsign: 'FIN8AF', classification: 'M/A319', origin: 'EFHK' },
  { callsign: 'SVA124', classification: 'H/B78X', origin: 'OEJN' },
  { callsign: 'ETH729', classification: 'H/A359', origin: 'LSGG' },
  { callsign: 'KAC114', classification: 'H/A338', origin: 'OKKK' },
  { callsign: 'PGT5816', classification: 'M/A21N', origin: 'LTFM' },
  { callsign: 'ABR9AN', classification: 'S/AT76', origin: 'LFPG' },
  { callsign: 'EAG19E', classification: 'S/AT76', origin: 'EGAC' },
  { callsign: 'EAI70B', classification: 'S/AT76', origin: 'EIDW' },
  { callsign: 'RYR9CU', classification: 'M/B38M', origin: 'EIDW' },
  { callsign: 'EXS6V', classification: 'M/B738', origin: 'LYTV' },
  { callsign: 'EZY62AQ', classification: 'M/A20N', origin: 'LTBS' },
  { callsign: 'NOZ1346', classification: 'M/B738', origin: 'ENGM' },
  { callsign: 'PGT3CH', classification: 'M/A21N', origin: 'LTFM' },
  { callsign: 'BBC207', classification: 'H/B788', origin: 'VGSY' },
  { callsign: 'EWG8AJ', classification: 'M/A319', origin: 'EDDL' },
  { callsign: 'ETD49D', classification: 'H/B77W', origin: 'OMAA' },
  { callsign: 'UAE1KM', classification: 'J/A388', origin: 'OMDB' },
  { callsign: 'AFR21JD', classification: 'M/E190', origin: 'LFPG' },
  { callsign: 'SWR8TZ', classification: 'M/BCS3', origin: 'LSZH' },
  { callsign: 'BEL9HZ', classification: 'M/A319', origin: 'EBBR' },
  { callsign: 'EJU95JC', classification: 'M/A319', origin: 'LEPA' },
  { callsign: 'SUS45U', classification: 'L/J328', origin: 'EKBI' },
  { callsign: 'RUK6TE', classification: 'M/B738', origin: 'GCLP' },
  { callsign: 'SIA51', classification: 'H/A359', origin: 'KIAH' },
  { callsign: 'SXS9VU', classification: 'M/B38M', origin: 'LTBS' },
  { callsign: 'THY3HP', classification: 'H/A333', origin: 'LTFM' },
  { callsign: 'SAS4608', classification: 'M/A20N', origin: 'EKCH' },
  { callsign: 'QTR91F', classification: 'H/A35K', origin: 'OTBD' },
  { callsign: 'QTR3OW', classification: 'H/A359', origin: 'OTBD' },
  { callsign: 'VLG737W', classification: 'M/A320', origin: 'LEBL' },
  { callsign: 'SHT2K', classification: 'M/A21N', origin: 'EGLL' },
  { callsign: 'IBS3693', classification: 'M/A320', origin: 'LEMD' },
  { callsign: 'TAP1313', classification: 'M/A20N', origin: 'LPPT' },
  { callsign: 'MSR782', classification: 'M/A21N', origin: 'HECA' },
  { callsign: 'LOG17ZA', classification: 'S/AT45', origin: 'EGPE' },
  { callsign: 'VJH824', classification: 'L/C56X', origin: 'EHAM' },
  { callsign: 'NJE311T', classification: 'L/E55P', origin: 'EHAM' },
  { callsign: 'ICE29E', classification: 'M/B38M', origin: 'BIRK' },
  { callsign: 'EAI70B', classification: 'S/AT76', origin: 'EIDW' },
  { callsign: 'NSZ4469', classification: 'M/B38M', origin: 'EKCH' },
  { callsign: 'SXN75A', classification: 'L/C525', origin: 'EGJB' },
  { callsign: 'EUK93H', classification: 'H/A333', origin: 'VTSP' },
  { callsign: 'GFA005', classification: 'H/B789', origin: 'OBBI' },
  { callsign: 'TOM60H', classification: 'H/B788', origin: 'VTSP' },
  { callsign: 'CHH753', classification: 'H/A333', origin: 'ZBAA' },
  { callsign: 'BRO926P', classification: 'M/B733', origin: 'EGBN' },
  { callsign: 'FHM8505', classification: 'M/A320', origin: 'LDDU' },
  { callsign: 'LGL451C', classification: 'S/DH8D', origin: 'ELLX' },
  { callsign: 'DLH7KY', classification: 'M/A21N', origin: 'EDDM' },
  { callsign: 'RYR36FA', classification: 'M/B38M', origin: 'LIPZ' },
  { callsign: 'EXS49TA', classification: 'M/B738', origin: 'LEPA' },
  { callsign: 'KLM48F', classification: 'M/E295', origin: 'EHAM' },
  { callsign: 'AUR679', classification: 'S/DH8D', origin: 'EGJB' },
  { callsign: 'EZY96RN', classification: 'M/A320', origin: 'LFPG' },
  { callsign: 'EZY37TB', classification: 'M/A320', origin: 'EGNS' },
  { callsign: 'RYR4GT', classification: 'M/B38M', origin: 'GCTS' },
  { callsign: 'VJH728', classification: 'S/E35L', origin: 'EHAM' },
]

export const getRandomFlightOption = () => {
  const flightIndex = Math.floor(Math.random() * remainingOptions.length)
  const flight = remainingOptions[flightIndex]
  remainingOptions.splice(flightIndex, 1)
  return flight
}
